name: build-windows

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure (CMake + Ninja)
        run: cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release

      - name: Build (script)
        run: ./scripts/compile.sh
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: keyleport-windows
          path: |
            build/keyleport.exe
